###

POST http://localhost:5000/api/courseunits/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTlhNDQyNDJhZDI5OWY5ZThiYzVjNyIsImlhdCI6MTcwNDYzOTI1OCwiZXhwIjoxNzA3MjMxMjU4fQ.LHNov2kgVD1l40FaABhVLej-kF8VRmIHmFS8rlAufyw

{
"name": "Criminal Law Course Unit",
"code": "CLCU",
"description": "An introductory course to programming concepts.",
"course":"65a386e888bd19cbb969568c"
}

###
GET http://localhost:5000/api/courseunits/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTZkZWE3YTQ3MjVmNzhlMjZlYjJjOSIsImlhdCI6MTcwNDM5OTI0NywiZXhwIjoxNzA2OTkxMjQ3fQ.ISxvmAuAXVYagKlXoKnEx3Ge0tXBhf81UpC0rVZbzKI

###
GET http://localhost:5000/api/courseunits/6597e3fb97d4d9309e9e3495
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTZkZWE3YTQ3MjVmNzhlMjZlYjJjOSIsImlhdCI6MTcwNDM5OTI0NywiZXhwIjoxNzA2OTkxMjQ3fQ.ISxvmAuAXVYagKlXoKnEx3Ge0tXBhf81UpC0rVZbzKI
