###
## REGISTER STUDENT
POST http://localhost:5000/api/lecturers/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTZkZWE3YTQ3MjVmNzhlMjZlYjJjOSIsImlhdCI6MTcwNDM5OTI0NywiZXhwIjoxNzA2OTkxMjQ3fQ.ISxvmAuAXVYagKlXoKnEx3Ge0tXBhf81UpC0rVZbzKI

{
    "firstName": "Anita",
    "secondName":"Wamaitha",
    "surName":"Nyamu",
    "email":"ngecu16@gmail.com",
    "password": "3W!W.:srzc4r^!P",
    "dob":"1999-01-01",
    "phone":"0722304537",
    "parent":"659712b5179e1385f2f0c27c",
    "gender":"Male"
}

###
GET http://localhost:5000/api/lecturers/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OTZkZWE3YTQ3MjVmNzhlMjZlYjJjOSIsImlhdCI6MTcwNDM5OTI0NywiZXhwIjoxNzA2OTkxMjQ3fQ.ISxvmAuAXVYagKlXoKnEx3Ge0tXBhf81UpC0rVZbzKI
