###
POST http://localhost:5000/api/mpesa/stkPush
Content-Type: application/json

{
    "phone":"254707583092",
    "amount":20,
    "Order_ID":"asdadasd"
}

###
POST https://sandbox.safaricom.co.ke/mpesa/qrcode/v1/generate
Content-Type: application/json