###
GET http://localhost:5000/api/schoolfees/student/659ac6107dd4cec223a10f08
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWFjNjExN2RkNGNlYzIyM2ExMGYwYyIsImlhdCI6MTcwNDkwODQ2NywiZXhwIjoxNzA3NTAwNDY3fQ.0tMAkWcD8BhEbDj3uan4b7ojIIBMZjPFs3l9PlRUpv8

###
GET http://localhost:5000/api/payment/
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTE2ZTY0NWIxYjBiZDQ1MjY0NWI1ZiIsImlhdCI6MTcwNTE3OTM2NywiZXhwIjoxNzA3NzcxMzY3fQ.0iBny7onxjXwjugFqLD_MnUAdaJ6UPZxY-QUZte1E6A