###
## REGISTER STUDENT
POST http://localhost:5000/api/students/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTQwZTQxM2YzY2E1NGViNWJhOTk1OCIsImlhdCI6MTcwNTI1MDQyMCwiZXhwIjoxNzA3ODQyNDIwfQ.GKFMSewseINWEqmPCMlN0BcqNRhya8GXWmX_5gNFq0w

{
  "email": "devngecu@gmail.com",
  "password": "password123",
  "firstName": "Robinson",
  "lastName": "Nyamu",
  "gender": "Mmale",
  "dob": "1999-07-07",
  "religion": "Christian",
  "phone": "0707583092",
  "nationalID": "ABC123456",
  "course": "6597e3fb97d4d9309e9e3493",
  "parents": [

    {
  "email": "parent6@example.com",
  "password": "password1234",
  "fullName": "John Doe2",
  "surname": "Smith2",
  "dateOfJoin": "2023-01-10T12:00:00Z",
  "dob": "1990-05-15",
  "phone": "1234567891",
  "gender": "Male",
  "status": true,
  "lastLoginDate": "2023-01-10T10:30:00Z",
  "lastLoginIp": "192.168.0.1"
}

],
  "status": true,
  "lastLoginDate": "2023-01-12T08:45:00Z",
  "lastLoginIp": "192.168.0.2"
}


###
GET http://localhost:5000/api/students/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWFjNTg4N2RkNGNlYzIyM2ExMGVmZCIsImlhdCI6MTcwNDY0MTk1MCwiZXhwIjoxNzA3MjMzOTUwfQ.zXWPCc2w3a1n_2d6o_8ReuhTW3vzgNbFFSr3DrzzB1o
