

export const CREATE_ACCOUNTANT_REQUEST = 'CREATE_ACCOUNTANT_REQUEST';
export const CREATE_ACCOUNTANT_SUCCESS = 'CREATE_ACCOUNTANT_SUCCESS';
export const CREATE_ACCOUNTANT_FAILURE = 'CREATE_ACCOUNTANT_FAILURE';

export const ACCOUNTANT_LIST_REQUEST = 'ACCOUNTANT_LIST_REQUEST';
export const ACCOUNTANT_LIST_SUCCESS = 'ACCOUNTANT_LIST_SUCCESS';
export const ACCOUNTANT_LIST_FAIL = 'ACCOUNTANT_LIST_FAIL';
export const ACCOUNTANT_LIST_RESET = 'ACCOUNTANT_LIST_RESET';


export const ACCOUNTANT_DETAILS_REQUEST = 'ACCOUNTANT_DETAILS_REQUEST';
export const ACCOUNTANT_DETAILS_SUCCESS = 'ACCOUNTANT_DETAILS_SUCCESS';
export const ACCOUNTANT_DETAILS_FAIL = 'ACCOUNTANT_DETAILS_FAIL';
export const ACCOUNTANT_DETAILS_RESET = 'ACCOUNTANT_DETAILS_RESET';


export const ACCOUNTANT_UPDATE_REQUEST = 'ACCOUNTANT_UPDATE_REQUEST';
export const ACCOUNTANT_UPDATE_SUCCESS = 'ACCOUNTANT_UPDATE_SUCCESS';
export const ACCOUNTANT_UPDATE_FAIL = 'ACCOUNTANT_UPDATE_FAIL';
export const ACCOUNTANT_UPDATE_RESET = 'ACCOUNTANT_UPDATE_RESET';

// ACCOUNTANT Delete Constants
export const ACCOUNTANT_DELETE_REQUEST = 'ACCOUNTANT_DELETE_REQUEST';
export const ACCOUNTANT_DELETE_SUCCESS = 'ACCOUNTANT_DELETE_SUCCESS';
export const ACCOUNTANT_DELETE_FAIL = 'ACCOUNTANT_DELETE_FAIL';
