// accountantConstants.js

export const CREATE_ACCOUNTANT_REQUEST = 'CREATE_ACCOUNTANT_REQUEST';
export const CREATE_ACCOUNTANT_SUCCESS = 'CREATE_ACCOUNTANT_SUCCESS';
export const CREATE_ACCOUNTANT_FAILURE = 'CREATE_ACCOUNTANT_FAILURE';
