// Assignment Constants
export const ASSIGNMENT_CREATE_REQUEST = 'ASSIGNMENT_CREATE_REQUEST';
export const ASSIGNMENT_CREATE_SUCCESS = 'ASSIGNMENT_CREATE_SUCCESS';
export const ASSIGNMENT_CREATE_FAIL = 'ASSIGNMENT_CREATE_FAIL';

export const ASSIGNMENT_LIST_REQUEST = 'ASSIGNMENT_LIST_REQUEST';
export const ASSIGNMENT_LIST_SUCCESS = 'ASSIGNMENT_LIST_SUCCESS';
export const ASSIGNMENT_LIST_FAIL = 'ASSIGNMENT_LIST_FAIL';

export const ASSIGNMENT_DETAILS_REQUEST = 'ASSIGNMENT_DETAILS_REQUEST';
export const ASSIGNMENT_DETAILS_SUCCESS = 'ASSIGNMENT_DETAILS_SUCCESS';
export const ASSIGNMENT_DETAILS_FAIL = 'ASSIGNMENT_DETAILS_FAIL';

// Submission Constants
export const SUBMISSION_CREATE_REQUEST = 'SUBMISSION_CREATE_REQUEST';
export const SUBMISSION_CREATE_SUCCESS = 'SUBMISSION_CREATE_SUCCESS';
export const SUBMISSION_CREATE_FAIL = 'SUBMISSION_CREATE_FAIL';

export const SUBMISSION_LIST_REQUEST = 'SUBMISSION_LIST_REQUEST';
export const SUBMISSION_LIST_SUCCESS = 'SUBMISSION_LIST_SUCCESS';
export const SUBMISSION_LIST_FAIL = 'SUBMISSION_LIST_FAIL';

export const SUBMISSION_DETAILS_REQUEST = 'SUBMISSION_DETAILS_REQUEST';
export const SUBMISSION_DETAILS_SUCCESS = 'SUBMISSION_DETAILS_SUCCESS';
export const SUBMISSION_DETAILS_FAIL = 'SUBMISSION_DETAILS_FAIL';
