// Attendance Create Constants
export const ATTENDANCE_CREATE_REQUEST = 'ATTENDANCE_CREATE_REQUEST';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE_CREATE_SUCCESS';
export const ATTENDANCE_CREATE_FAIL = 'ATTENDANCE_CREATE_FAIL';

// Attendance List Constants
export const ATTENDANCE_LIST_REQUEST = 'ATTENDANCE_LIST_REQUEST';
export const ATTENDANCE_LIST_SUCCESS = 'ATTENDANCE_LIST_SUCCESS';
export const ATTENDANCE_LIST_FAIL = 'ATTENDANCE_LIST_FAIL';
export const ATTENDANCE_LIST_RESET = 'ATTENDANCE_LIST_RESET';

// Attendance Details Constants
export const ATTENDANCE_DETAILS_REQUEST = 'ATTENDANCE_DETAILS_REQUEST';
export const ATTENDANCE_DETAILS_SUCCESS = 'ATTENDANCE_DETAILS_SUCCESS';
export const ATTENDANCE_DETAILS_FAIL = 'ATTENDANCE_DETAILS_FAIL';
export const ATTENDANCE_DETAILS_RESET = 'ATTENDANCE_DETAILS_RESET';
