export const CHAT_FETCH_MESSAGES_REQUEST = 'CHAT_FETCH_MESSAGES_REQUEST';
export const CHAT_FETCH_MESSAGES_SUCCESS = 'CHAT_FETCH_MESSAGES_SUCCESS';
export const CHAT_FETCH_MESSAGES_FAILURE = 'CHAT_FETCH_MESSAGES_FAILURE';

export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAILURE = 'CHAT_SEND_MESSAGE_FAILURE';

export const CHAT_JOIN_CONVERSATION_REQUEST = 'CHAT_JOIN_CONVERSATION_REQUEST';
export const CHAT_JOIN_CONVERSATION_SUCCESS = 'CHAT_JOIN_CONVERSATION_SUCCESS';
export const CHAT_JOIN_CONVERSATION_FAILURE = 'CHAT_JOIN_CONVERSATION_FAILURE';


export const CHAT_LEAVE_CONVERSATION_REQUEST = 'CHAT_LEAVE_CONVERSATION_REQUEST';
export const CHAT_LEAVE_CONVERSATION_SUCCESS = 'CHAT_LEAVE_CONVERSATION_SUCCESS';
export const CHAT_LEAVE_CONVERSATION_FAILURE = 'CHAT_LEAVE_CONVERSATION_FAILURE';

export const CHAT_EDIT_MESSAGE_REQUEST = 'CHAT_EDIT_MESSAGE_REQUEST';
export const CHAT_EDIT_MESSAGE_SUCCESS = 'CHAT_EDIT_MESSAGE_SUCCESS';
export const CHAT_EDIT_MESSAGE_FAILURE = 'CHAT_EDIT_MESSAGE_FAILURE';

export const CHAT_DELETE_MESSAGE_REQUEST = 'CHAT_DELETE_MESSAGE_REQUEST';
export const CHAT_DELETE_MESSAGE_SUCCESS = 'CHAT_DELETE_MESSAGE_SUCCESS';
export const CHAT_DELETE_MESSAGE_FAILURE = 'CHAT_DELETE_MESSAGE_FAILURE';

export const CHAT_ACTIVE_CONVERSATION_REQUEST = 'CHAT_ACTIVE_CONVERSATION_REQUEST';
export const CHAT_ACTIVE_CONVERSATION_SUCCESS = 'CHAT_ACTIVE_CONVERSATION_REQUEST';
export const CHAT_ACTIVE_CONVERSATION_FAILURE = 'CHAT_ACTIVE_CONVERSATION_REQUEST';
