// constants.js

// Conversation constants
export const CREATE_CONVERSATION_REQUEST = 'CREATE_CONVERSATION_REQUEST';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAIL = 'CREATE_CONVERSATION_FAIL';

export const GET_ALL_CONVERSATIONS_REQUEST = 'GET_ALL_CONVERSATIONS_REQUEST';
export const GET_ALL_CONVERSATIONS_SUCCESS = 'GET_ALL_CONVERSATIONS_SUCCESS';
export const GET_ALL_CONVERSATIONS_FAIL = 'GET_ALL_CONVERSATIONS_FAIL';

export const GET_USER_CONVERSATIONS_REQUEST = 'GET_USER_CONVERSATIONS_REQUEST';
export const GET_USER_CONVERSATIONS_SUCCESS = 'GET_USER_CONVERSATIONS_SUCCESS';
export const GET_USER_CONVERSATIONS_FAIL = 'GET_USER_CONVERSATIONS_FAIL';
