// courseUnitConstants.js

export const COURSE_UNIT_CREATE_REQUEST = 'COURSE_UNIT_CREATE_REQUEST';
export const COURSE_UNIT_CREATE_SUCCESS = 'COURSE_UNIT_CREATE_SUCCESS';
export const COURSE_UNIT_CREATE_FAIL = 'COURSE_UNIT_CREATE_FAIL';

export const GET_ALL_COURSE_UNITS_REQUEST = 'GET_ALL_COURSE_UNITS_REQUEST';
export const GET_ALL_COURSE_UNITS_SUCCESS = 'GET_ALL_COURSE_UNITS_SUCCESS';
export const GET_ALL_COURSE_UNITS_FAIL = 'GET_ALL_COURSE_UNITS_FAIL';

export const GET_COURSE_UNITS_BY_COURSE_REQUEST = 'GET_COURSE_UNITS_BY_COURSE_REQUEST';
export const GET_COURSE_UNITS_BY_COURSE_SUCCESS = 'GET_COURSE_UNITS_BY_COURSE_SUCCESS';
export const GET_COURSE_UNITS_BY_COURSE_FAIL = 'GET_COURSE_UNITS_BY_COURSE_FAIL';
