// examResultConstants.js

export const EXAM_RESULT_CREATE_REQUEST = 'EXAM_RESULT_CREATE_REQUEST';
export const EXAM_RESULT_CREATE_SUCCESS = 'EXAM_RESULT_CREATE_SUCCESS';
export const EXAM_RESULT_CREATE_FAIL = 'EXAM_RESULT_CREATE_FAIL';

export const GET_ALL_EXAM_RESULTS_REQUEST = 'GET_ALL_EXAM_RESULTS_REQUEST';
export const GET_ALL_EXAM_RESULTS_SUCCESS = 'GET_ALL_EXAM_RESULTS_SUCCESS';
export const GET_ALL_EXAM_RESULTS_FAIL = 'GET_ALL_EXAM_RESULTS_FAIL';

export const GET_EXAM_RESULT_DETAILS_REQUEST = 'GET_EXAM_RESULT_DETAILS_REQUEST';
export const GET_EXAM_RESULT_DETAILS_SUCCESS = 'GET_EXAM_RESULT_DETAILS_SUCCESS';
export const GET_EXAM_RESULT_DETAILS_FAIL = 'GET_EXAM_RESULT_DETAILS_FAIL';

export const EXAM_RESULT_UPDATE_REQUEST = 'EXAM_RESULT_UPDATE_REQUEST';
export const EXAM_RESULT_UPDATE_SUCCESS = 'EXAM_RESULT_UPDATE_SUCCESS';
export const EXAM_RESULT_UPDATE_FAIL = 'EXAM_RESULT_UPDATE_FAIL';

export const EXAM_RESULT_DELETE_REQUEST = 'EXAM_RESULT_DELETE_REQUEST';
export const EXAM_RESULT_DELETE_SUCCESS = 'EXAM_RESULT_DELETE_SUCCESS';
export const EXAM_RESULT_DELETE_FAIL = 'EXAM_RESULT_DELETE_FAIL';

export const GET_EXAM_RESULTS_BY_STUDENT_REQUEST = 'GET_EXAM_RESULTS_BY_STUDENT_REQUEST';
export const GET_EXAM_RESULTS_BY_STUDENT_SUCCESS = 'GET_EXAM_RESULTS_BY_STUDENT_SUCCESS';
export const GET_EXAM_RESULTS_BY_STUDENT_FAIL = 'GET_EXAM_RESULTS_BY_STUDENT_FAIL';