export const EXAM_CREATE_REQUEST = 'EXAM_CREATE_REQUEST';
export const EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS';
export const EXAM_CREATE_FAIL = 'EXAM_CREATE_FAIL';

export const GET_ALL_EXAMS_REQUEST = 'GET_ALL_EXAMS_REQUEST';
export const GET_ALL_EXAMS_SUCCESS = 'GET_ALL_EXAMS_SUCCESS';
export const GET_ALL_EXAMS_FAIL = 'GET_ALL_EXAMS_FAIL';

export const EXAM_DETAILS_REQUEST = 'EXAM_DETAILS_REQUEST';
export const EXAM_DETAILS_SUCCESS = 'EXAM_DETAILS_SUCCESS';
export const EXAM_DETAILS_FAIL = 'EXAM_DETAILS_FAIL';

export const EXAM_UPDATE_REQUEST = 'EXAM_UPDATE_REQUEST';
export const EXAM_UPDATE_SUCCESS = 'EXAM_UPDATE_SUCCESS';
export const EXAM_UPDATE_FAIL = 'EXAM_UPDATE_FAIL';

export const EXAM_DELETE_REQUEST = 'EXAM_DELETE_REQUEST';
export const EXAM_DELETE_SUCCESS = 'EXAM_DELETE_SUCCESS';
export const EXAM_DELETE_FAIL = 'EXAM_DELETE_FAIL';