// examConstants.js

export const EXAM_CREATE_REQUEST = 'EXAM_CREATE_REQUEST';
export const EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS';
export const EXAM_CREATE_FAIL = 'EXAM_CREATE_FAIL';

export const GET_ALL_EXAMS_REQUEST = 'GET_ALL_EXAMS_REQUEST';
export const GET_ALL_EXAMS_SUCCESS = 'GET_ALL_EXAMS_SUCCESS';
export const GET_ALL_EXAMS_FAIL = 'GET_ALL_EXAMS_FAIL';