// feeConstants.js

export const CREATE_FEES_REQUEST = 'CREATE_FEES_REQUEST';
export const CREATE_FEES_SUCCESS = 'CREATE_FEES_SUCCESS';
export const CREATE_FEES_FAIL = 'CREATE_FEES_FAIL';

export const GET_ALL_FEES_REQUEST = 'GET_ALL_FEES_REQUEST';
export const GET_ALL_FEES_SUCCESS = 'GET_ALL_FEES_SUCCESS';
export const GET_ALL_FEES_FAIL = 'GET_ALL_FEES_FAIL';

export const GET_FEES_BY_STUDENT_REQUEST = 'GET_FEES_BY_STUDENT_REQUEST';
export const GET_FEES_BY_STUDENT_SUCCESS = 'GET_FEES_BY_STUDENT_SUCCESS';
export const GET_FEES_BY_STUDENT_FAIL = 'GET_FEES_BY_STUDENT_FAIL';

export const MARK_FEES_AS_PAID_REQUEST = 'MARK_FEES_AS_PAID_REQUEST';
export const MARK_FEES_AS_PAID_SUCCESS = 'MARK_FEES_AS_PAID_SUCCESS';
export const MARK_FEES_AS_PAID_FAIL = 'MARK_FEES_AS_PAID_FAIL';
