// Lecturer Create Constants
export const LECTURER_CREATE_REQUEST = 'LECTURER_CREATE_REQUEST';
export const LECTURER_CREATE_SUCCESS = 'LECTURER_CREATE_SUCCESS';
export const LECTURER_CREATE_FAIL = 'LECTURER_CREATE_FAIL';

// Lecturer List Constants
export const LECTURER_LIST_REQUEST = 'LECTURER_LIST_REQUEST';
export const LECTURER_LIST_SUCCESS = 'LECTURER_LIST_SUCCESS';
export const LECTURER_LIST_FAIL = 'LECTURER_LIST_FAIL';
export const LECTURER_LIST_RESET = 'LECTURER_LIST_RESET';

// Lecturer Details Constants
export const LECTURER_DETAILS_REQUEST = 'LECTURER_DETAILS_REQUEST';
export const LECTURER_DETAILS_SUCCESS = 'LECTURER_DETAILS_SUCCESS';
export const LECTURER_DETAILS_FAIL = 'LECTURER_DETAILS_FAIL';
export const LECTURER_DETAILS_RESET = 'LECTURER_DETAILS_RESET';

// Lecturer Update Constants
export const LECTURER_UPDATE_REQUEST = 'LECTURER_UPDATE_REQUEST';
export const LECTURER_UPDATE_SUCCESS = 'LECTURER_UPDATE_SUCCESS';
export const LECTURER_UPDATE_FAIL = 'LECTURER_UPDATE_FAIL';
export const LECTURER_UPDATE_RESET = 'LECTURER_UPDATE_RESET';

// Lecturer Delete Constants
export const LECTURER_DELETE_REQUEST = 'LECTURER_DELETE_REQUEST';
export const LECTURER_DELETE_SUCCESS = 'LECTURER_DELETE_SUCCESS';
export const LECTURER_DELETE_FAIL = 'LECTURER_DELETE_FAIL';
