// STK Push constants
export const INITIATE_STK_PUSH_REQUEST = 'INITIATE_STK_PUSH_REQUEST';
export const INITIATE_STK_PUSH_SUCCESS = 'INITIATE_STK_PUSH_SUCCESS';
export const INITIATE_STK_PUSH_FAIL = 'INITIATE_STK_PUSH_FAIL';

// STK Push Callback constants
export const STK_PUSH_CALLBACK_REQUEST = 'STK_PUSH_CALLBACK_REQUEST';
export const STK_PUSH_CALLBACK_SUCCESS = 'STK_PUSH_CALLBACK_SUCCESS';
export const STK_PUSH_CALLBACK_FAIL = 'STK_PUSH_CALLBACK_FAIL';

// Confirm Payment constants
export const CONFIRM_PAYMENT_REQUEST = 'CONFIRM_PAYMENT_REQUEST';
export const CONFIRM_PAYMENT_SUCCESS = 'CONFIRM_PAYMENT_SUCCESS';
export const CONFIRM_PAYMENT_FAIL = 'CONFIRM_PAYMENT_FAIL';