// paymentTransactionConstants.js

// Constants for fetching all payment transactions
export const PAYMENT_TRANSACTION_LIST_REQUEST = 'PAYMENT_TRANSACTION_LIST_REQUEST';
export const PAYMENT_TRANSACTION_LIST_SUCCESS = 'PAYMENT_TRANSACTION_LIST_SUCCESS';
export const PAYMENT_TRANSACTION_LIST_FAIL = 'PAYMENT_TRANSACTION_LIST_FAIL';

// Constants for fetching a single payment transaction
export const PAYMENT_TRANSACTION_DETAILS_REQUEST = 'PAYMENT_TRANSACTION_DETAILS_REQUEST';
export const PAYMENT_TRANSACTION_DETAILS_SUCCESS = 'PAYMENT_TRANSACTION_DETAILS_SUCCESS';
export const PAYMENT_TRANSACTION_DETAILS_FAIL = 'PAYMENT_TRANSACTION_DETAILS_FAIL';

// Constants for creating a payment transaction
export const PAYMENT_TRANSACTION_CREATE_REQUEST = 'PAYMENT_TRANSACTION_CREATE_REQUEST';
export const PAYMENT_TRANSACTION_CREATE_SUCCESS = 'PAYMENT_TRANSACTION_CREATE_SUCCESS';
export const PAYMENT_TRANSACTION_CREATE_FAIL = 'PAYMENT_TRANSACTION_CREATE_FAIL';

// Constants for updating a payment transaction
export const PAYMENT_TRANSACTION_UPDATE_REQUEST = 'PAYMENT_TRANSACTION_UPDATE_REQUEST';
export const PAYMENT_TRANSACTION_UPDATE_SUCCESS = 'PAYMENT_TRANSACTION_UPDATE_SUCCESS';
export const PAYMENT_TRANSACTION_UPDATE_FAIL = 'PAYMENT_TRANSACTION_UPDATE_FAIL';

// Constants for deleting a payment transaction
export const PAYMENT_TRANSACTION_DELETE_REQUEST = 'PAYMENT_TRANSACTION_DELETE_REQUEST';
export const PAYMENT_TRANSACTION_DELETE_SUCCESS = 'PAYMENT_TRANSACTION_DELETE_SUCCESS';
export const PAYMENT_TRANSACTION_DELETE_FAIL = 'PAYMENT_TRANSACTION_DELETE_FAIL';

export const PAYMENT_TRANSACTION_BY_FEE_REQUEST = 'PAYMENT_TRANSACTION_BY_FEE_REQUEST';
export const PAYMENT_TRANSACTION_BY_FEE_SUCCESS = 'PAYMENT_TRANSACTION_BY_FEE_SUCCESS';
export const PAYMENT_TRANSACTION_BY_FEE_FAIL = 'PAYMENT_TRANSACTION_BY_FEE_FAIL';