export const SCHOOL_CREATE_REQUEST = 'SCHOOL_CREATE_REQUEST';
export const SCHOOL_CREATE_SUCCESS = 'SCHOOL_CREATE_SUCCESS';
export const SCHOOL_CREATE_FAIL = 'SCHOOL_CREATE_FAIL';

export const SCHOOL_LIST_REQUEST = 'SCHOOL_LIST_REQUEST';
export const SCHOOL_LIST_SUCCESS = 'SCHOOL_LIST_SUCCESS';
export const SCHOOL_LIST_FAIL = 'SCHOOL_LIST_FAIL';
export const SCHOOL_LIST_RESET = 'SCHOOL_LIST_RESET';

export const SCHOOL_DETAILS_REQUEST = 'SCHOOL_DETAILS_REQUEST';
export const SCHOOL_DETAILS_SUCCESS = 'SCHOOL_DETAILS_SUCCESS';
export const SCHOOL_DETAILS_FAIL = 'SCHOOL_DETAILS_FAIL';
export const SCHOOL_DETAILS_RESET = 'SCHOOL_DETAILS_RESET';

export const SCHOOL_UPDATE_REQUEST = 'SCHOOL_UPDATE_REQUEST';
export const SCHOOL_UPDATE_SUCCESS = 'SCHOOL_UPDATE_SUCCESS';
export const SCHOOL_UPDATE_FAIL = 'SCHOOL_UPDATE_FAIL';
export const SCHOOL_UPDATE_RESET = 'SCHOOL_UPDATE_RESET';

export const SCHOOL_DELETE_REQUEST = 'SCHOOL_DELETE_REQUEST';
export const SCHOOL_DELETE_SUCCESS = 'SCHOOL_DELETE_SUCCESS';
export const SCHOOL_DELETE_FAIL = 'SCHOOL_DELETE_FAIL';
