// timetableConstants.js

export const TIMETABLE_LIST_REQUEST = 'TIMETABLE_LIST_REQUEST';
export const TIMETABLE_LIST_SUCCESS = 'TIMETABLE_LIST_SUCCESS';
export const TIMETABLE_LIST_FAIL = 'TIMETABLE_LIST_FAIL';

export const TIMETABLE_DETAILS_REQUEST = 'TIMETABLE_DETAILS_REQUEST';
export const TIMETABLE_DETAILS_SUCCESS = 'TIMETABLE_DETAILS_SUCCESS';
export const TIMETABLE_DETAILS_FAIL = 'TIMETABLE_DETAILS_FAIL';

export const TIMETABLE_CREATE_REQUEST = 'TIMETABLE_CREATE_REQUEST';
export const TIMETABLE_CREATE_SUCCESS = 'TIMETABLE_CREATE_SUCCESS';
export const TIMETABLE_CREATE_FAIL = 'TIMETABLE_CREATE_FAIL';

export const TIMETABLE_UPDATE_REQUEST = 'TIMETABLE_UPDATE_REQUEST';
export const TIMETABLE_UPDATE_SUCCESS = 'TIMETABLE_UPDATE_SUCCESS';
export const TIMETABLE_UPDATE_FAIL = 'TIMETABLE_UPDATE_FAIL';

export const TIMETABLE_DELETE_REQUEST = 'TIMETABLE_DELETE_REQUEST';
export const TIMETABLE_DELETE_SUCCESS = 'TIMETABLE_DELETE_SUCCESS';
export const TIMETABLE_DELETE_FAIL = 'TIMETABLE_DELETE_FAIL';


export const TIMETABLE_BY_COURSE_REQUEST = 'TIMETABLE_BY_COURSE_REQUEST';
export const TIMETABLE_BY_COURSE_SUCCESS = 'TIMETABLE_BY_COURSE_SUCCESS';
export const TIMETABLE_BY_COURSE_FAIL = 'TIMETABLE_BY_COURSE_FAIL';
